### ISSUE TITLE
项目跑不起来，swoole版本4.4.4

### ISSUE THREAD

**Issue by lidaqi001** [swoole-plus/webrtc#1]
WebSocket connection to 'ws://118.24.26.76:9502/' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by sy-records** [comment]
升级swoole版本吧，4.4lts或者4.5

**Comment by lidaqi001** [comment]
升级了swoole版本，跑是跑起来了，但是。。。

**Comment by lidaqi001** [comment]
这个项目写完了吗？处理语音或视频数据流的代码在哪里==
